# Generated by Django 4.1.7 on 2023-03-14 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='month_year',
        ),
    ]
